# Generated by Django 4.1.5 on 2023-01-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
