# Generated by Django 4.1.5 on 2023-01-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_lessons', '0002_alter_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Lesson',
            new_name='lesson',
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
