# Generated by Django 4.1.5 on 2023-02-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
