# Generated by Django 4.1.5 on 2023-02-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_payment_status_alter_order_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
