# Generated by Django 4.1.5 on 2023-02-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='randomID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
