# Generated by Django 4.1.5 on 2023-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_file',
        ),
        migrations.AddField(
            model_name='product',
            name='video_file_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
